### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by abcodefg** [abcodefg/todo-repository#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성 기능

###  해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Controller 클래스 postTodo 메서드 구현
2. [ ] Service 클래스 createTodo 메서드 구현
3. [ ] 생성 메서드 Test case 작성 및 테스트
4. [ ] Postman으로 POST 요청 후, h2 DB에서  확인

### 예상 작업 시간
1h
